INSERT INTO AGENDA (NAMECOMMITMENT, LOCALCOMMITMENT, DATE) VALUES ('Salao de Beleza', 'Avenida das Laranjeiras,100, Itu-SP', '08/12/2024');
INSERT INTO AGENDA (NAMECOMMITMENT, LOCALCOMMITMENT, DATE) VALUES ('Prova Economia', 'Fatec Itu-SP', '09/12/2024');
INSERT INTO AGENDA (NAMECOMMITMENT, LOCALCOMMITMENT, DATE) VALUES ('Dentista', 'Rua Floriano Peixoto, 884 - Centro, Itu-SP', '11/12/2024');
INSERT INTO AGENDA (NAMECOMMITMENT, LOCALCOMMITMENT, DATE) VALUES ('Cinema', 'Plaza Shopping Itu', '14/12/2024');